# Makefile for interpolation template
#
# Add your headerfile to the sineTest: line.

sineTest: sineTest.h sineTest.cpp LinearSine.h ChebSine.h
	g++ -o sineTest sineTest.cpp

all: sineTest

clear:
	rm -f sineTest